version: '3'

services:
  web:
    build:
      # Dockerfile の app のコピーのために必要なパス指定
      context: ../
      # context のパスから見た Dockerfile の場所
      dockerfile: docker/Dockerfile
    volumes:
      - /C/Users/kenta/IdeaProjects/spring-boot-docker:/app
    ports:
      - "8080:8080"
